from PyQt5.QtWidgets import QApplication, QLabel, QGridLayout, QWidget, QPushButton
app = QApplication([])
window = QWidget() 
layout = QGridLayout()
layout.addWidget(QPushButton('1'), 0, 0)
layout.addWidget(QPushButton('2'), 0, 1)
layout.addWidget(QPushButton('3'), 0, 2)
layout.addWidget(QPushButton('+'), 0, 3)
layout.addWidget(QPushButton('4'), 1, 0)
layout.addWidget(QPushButton('5'), 1, 1)
layout.addWidget(QPushButton('6'), 1, 2)
layout.addWidget(QPushButton('-'), 1, 3)
layout.addWidget(QPushButton('7'), 2, 0)
layout.addWidget(QPushButton('8'), 2, 1)
layout.addWidget(QPushButton('9'), 2, 2)
layout.addWidget(QPushButton('*'), 2, 3)
layout.addWidget(QPushButton('0'), 3, 0)
layout.addWidget(QPushButton('/'), 3, 1)
layout.addWidget(QPushButton('='), 3, 2)
window.setLayout(layout)
window.show()
#label = QLabel('Hello World!')
#label.show()
app.exec_()
